app/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    users = db.relationship('User', backref='role')

    def __repr__(self):
        return '<Role %r>' % self.name
class Produto(db.Model):
    __tablename__ = 'produtos'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    preco = db.Column(db.Integer)
    peso = db.Column(db.Integer)
    estoque = db.Column(db.Integer)

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    name = db.Column(db.String(64), unique=False, index=True)
    email = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User %r>' % self.username
    
    @property
    def password(self):
        raise AttributeError('password is not readable')
    
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)
    
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, ValidationError, IntegerField
from wtforms.validators import DataRequired
from app.models import User


class NameForm(FlaskForm):
    username = StringField('Digite seu login', validators=[DataRequired()])
    password = PasswordField('Digite sua senha', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    name = StringField('Digite seu nome', validators=[DataRequired()])
    username = StringField('Digite seu login', validators=[DataRequired()])
    email = StringField('Digite seu email', validators=[DataRequired()])
    password = PasswordField('Digite sua senha', validators=[DataRequired()])
    submit = SubmitField('Cadastrar')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError("Usuário já registrado.")


class ProdutoForm(FlaskForm):
    name = StringField('Nome do produto', validators=[DataRequired()])
    preco = IntegerField('Preço do produto', validators=[DataRequired()])
    peso = IntegerField('Quantidade por embalagem', validators=[DataRequired()])
    estoque = IntegerField('Quantidade em estoque', validators=[DataRequired()])
    submit = SubmitField('Cadastrar')


class EditProductForm(FlaskForm):
    name = StringField('Nome do produto', validators=[DataRequired()])
    preco = IntegerField('Preço do produto', validators=[DataRequired()])
    peso = IntegerField('Quantidade por embalagem', validators=[DataRequired()])
    estoque = IntegerField('Quantidade em estoque', validators=[DataRequired()])
    submit = SubmitField('Enviar')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
config = Config()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)
    config.init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, forms

app/main/views.py
from flask import flash, redirect, render_template, session, url_for, request
from flask_login import login_required
from flask_login import login_required, login_user, logout_user, current_user
from app.models import Role, User, Produto
from app import db
from . import main
from .forms import NameForm, ProdutoForm, RegistrationForm, EditProductForm


@main.route('/', methods=['GET', 'POST'])
def login():
    form = NameForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user)
            return redirect(url_for('main.tabela'))
        flash('Invalid username or password.')
    return render_template('index.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out')
    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    roles = Role.query.all()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            name=form.name.data,
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()
        flash('Usuário registrado!')
        return redirect(url_for('main.login'))
    return render_template('cadastro.html', form=form, roles=roles)



@main.route('/tabela', methods=['GET', 'POST'])
@login_required
def tabela():
    roles = Role.query.all()
    produtos = Produto.query.all()
    return render_template('tabela.html', roles=roles, produtos=produtos)


@main.route('/produto', methods=['GET', 'POST'])
@login_required
def add_produto():
    user_id = current_user.get_id()
    form = ProdutoForm()
    roles = Role.query.all()
    if current_user.role_id != 1:
        return redirect(url_for('main.tabela'))
    if form.validate_on_submit():
        new_produto = Produto()
        new_produto.name = form.name.data
        new_produto.preco = form.preco.data
        new_produto.peso = form.peso.data
        new_produto.estoque = form.estoque.data
        db.session.add(new_produto)
        db.session.commit()
        flash('Produto cadastrado com sucesso.')
        return redirect(url_for('main.tabela'))
    return render_template('produto.html', form=form, roles=roles, user=user_id)


@main.route('/editar_produto/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_product(id):
    produto = Produto.query.get_or_404(id)
    form = EditProductForm(produto=produto)
    if form.validate_on_submit():
        produto.name = form.name.data
        produto.preco = form.preco.data
        produto.peso = form.peso.data
        produto.estoque = form.estoque.data
        db.session.add(produto)
        db.session.commit()
        flash('Produto editado com sucesso!')
        return redirect(url_for('main.tabela'))
    form.name.data = produto.name
    form.preco.data = produto.preco
    form.peso.data = produto.peso
    form.estoque.data = produto.estoque
    return render_template('editar_produto.html', form=form, produto=produto.name)

app/templates/add_role.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
    <h1>Funções cadastradas</h1>
    <ul>
    {% for role in roles %}
            <li>{{ role.name }} </li>
    {% endfor %}
    </ul>
    <hr>
    <h1>Adicionar Funções</h1>
    {{ wtf.quick_form(form) }}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Pojeto2</title>
	<link rel="stylesheet" href="../static/bootstrap-4.3.1-dist/css/bootstrap.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
	<link rel="stylesheet" href="../static/css/tabela.css">
	<link rel="stylesheet" href="../static/css/cadastro.css">
</head>
<html>
	<header>
		<div class="row">
				<div class="col-md-1"><img src="../static/img/m.jpg" class="imagem"></div>
				<div class="col-md-11">
					<nav class="navbar navbar-expand-lg navbar-light">
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="navbar-nav">
								{% if current_user.is_authenticated %}
								<li class="nav-item">
									 <a class="nav-link" href="{{ url_for('main.tabela')}}">Home</a>
								</li>
								{% else %}
								<li class="nav-item">
									 <a class="nav-link" href="{{ url_for('main.login')}}">Home</a>
								</li>
								{% endif %}
								<li class="nav-item active">
									 <a class="nav-link" href="#">Produtos</a>
								</li>
								<li class="nav-item">
									 <a class="nav-link" href="#">Serviços</a>
								</li>
								<li class="nav-item">
									 <a class="nav-link" href="#">Sobre</a>
								</li>
								<li class="nav-item">
									 <a class="nav-link" href="#">Contato</a>
								</li>
								{% if current_user.is_authenticated %}
								{% if current_user.role_id == 1 %}
								<li class="nav-item">
									<a href="{{ url_for('main.add_produto')}}" class="nav-link">Adicionar Produtos</a>
								</li>
								{% endif %}
                        			<li class="nav-item">
                            			<a href="{{ url_for('main.logout') }}" class="nav-link">Logout</a>
                        			</li>
                                {% else %}
                                <li class="nav-item">
                                    <a href="{{url_for('main.login')}}" class="nav-link">Login</a>
                                </li>
								{% endif %}
							</ul>
						</div>
					</nav>
				</div>
			</div>
    </header>
    <body>
        {% block content %}
        {% endblock %}
    </body>
    <footer>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<h3>Acesse nossas redes sociais</h3>
				<div class="icones">
				<span class="fab fa-facebook"></span>
				<span class="fab fa-instagram"></span>
				<span class="fab fa-twitter"></span>
				<span class="fab fa-linkedin-in iconefinal"></span>
			</div>
			</div>
			<div class="col-md-2"></div>
		</div>
	</footer>
</html>

app/templates/cadastro.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
	{% block content%}
		<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md4 principal">
			<h2 class="mensagem">Cadastre-se para ver nossos produtos</h2>
			{{ wtf.quick_form(form) }}
		</div>
		<div class="col-md-4"></div>
	</div>
{% endblock %}

app/templates/editar_produto.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6 principal">
			<h2 class="mensagem">Editar Produto</h2>
			{{ wtf.quick_form(form) }}
		</div>
		<div class="col-md-3"></div>
	</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
{% import "bootstrap/wtf.html" as wtf %}
<html>
<head>
	<meta charset="utf-8" />
	<title>Projeto2</title>
	<link rel="stylesheet" href="../static/css/main.css">
    <link rel="stylesheet" href="../static/bootstrap/css/bootstrap.css">
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
</head>
<body>
	<header>
		<div class="row">
			<div class="col-md-12">
				<p class="boasvindas">Venha Comprar</p>
				<p class="boasvindas">Conosco!</p>
			</div>
		</div>
	</header>
	<div class="row">
		<div class="col-md-4"></div>
		<div class="col-md-4 principal">
				<h2 class="mensagem">Faça login para ver nossos produtos!</h2>
    			{{ wtf.quick_form(form) }}
				<a href="{{ url_for('main.register') }}" class="btn btn-primary">Criar conta</a>
			{% for message in get_flashed_messages() %}
			<div class="alert alert-warning">
                {{ message }}
            </div>
        {% endfor %}
		</div>
		<div class="col-md-4"></div>
	</div>
</div>
<script type="text/javascript" href="bootstrap/js/bootstrap.js"></script>
</body>
</html>

app/templates/produto.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
	{% block content %}
    <div class="row">
		<div class="col-md-4"></div>
		<div class="col-md4 principal">
			<h2 class="mensagem">Cadastrar novo produto</h2>
			{{ wtf.quick_form(form) }}
		</div>
		<div class="col-md-4"></div>
	</div>
    {% endblock %}

app/templates/tabela.html
{% extends "base.html" %}
	{% block content %}
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<table class="tabela">
				<colgroup>
					<col width="10%">
					<col width="15%">
					<col width="15%">
					<col width="15%">
					<col width="15%">
				</colgroup>
			{% for message in get_flashed_messages() %}
				<div class="alert alert-warning">
					{{ message }}
				</div>
        {% endfor %}
				<thead>
					<tr>
						<th colspan="6">Lista de Produtos</th>
					</tr>
					<tr>
						<th></th>
						<th>Produto</th>
						<th>Preço</th>
						<th>Qtd/Embalagem</th>
						<th>Qtd em Estoque</th>
					</tr>
				</thead>
				<tbody align="Center">
				{% for produto in produtos %}
					<tr>
						<td><img src="../static/img/download.png"></td>
						{% if current_user.role_id == 1 %}
						<td class="editar_produto"><a href="/editar_produto/{{ produto.id }}">{{produto.name}}</a></td>
						{% else %}
						<td>{{produto.name}}</td>
						{% endif %}
						<td>{{produto.preco}}</td>
						<td>{{produto.peso}}</td>
						<td>{{produto.estoque}} unidades</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-md-1"></div>
	</div>
	{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block title %}
    Minha projeto - Usuário
{% endblock %}

{% block page_content %}
    <h1>Olá, {{ name }}</h1>
{% endblock %}